/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the java Plugin to add support for Java.
    java
    checkstyle
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
}

configure<CheckstyleExtension> {
    toolVersion = "8.38"
}

dependencies {

    implementation("org.eclipse.microprofile", "microprofile", "3.3")

    implementation("jakarta.platform", "jakarta.jakartaee-web-api", "8.0.0")

    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.0")
    testImplementation("org.junit.vintage:junit-vintage-engine:5.7.0")

    // Mockito
    testImplementation("org.mockito:mockito-core:2.+")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.7.0")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
