---
- name: m-manager
  hostname: manager
  ip: 172.16.0.2
  memory: 2048
  cpus: 2
  role: manager

- name: web-app
  hostname: webapp
  ip: 172.16.0.3
  memory: 1024
  cpus: 1
  role: front-end

- name: api
  hostname: api
  ip: 172.16.0.4
  memory: 1024
  cpus: 1
  role: back-end

- name: db
  hostname: db
  ip: 172.16.0.5
  memory: 1024
  cpus: 2
  role: dabase