/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("br.co.familias.java-library-conventions")
    java
}

version = "1.0.0-SNAPSHOT"

sourceSets {
    test {
        resources {
            srcDir("src/test/resources")
        }
    }
}

dependencies {
    implementation(project(":model"))
    // https://mvnrepository.com/artifact/org.hsqldb/hsqldb
    testImplementation("org.hsqldb", "hsqldb", "2.4.0")

    // https://mvnrepository.com/artifact/org.jboss.weld/weld-junit5
    testImplementation("org.jboss.weld", "weld-junit5", "2.0.1.Final")

    // https://mvnrepository.com/artifact/org.hibernate/hibernate-core
    testImplementation("org.hibernate", "hibernate-core", "5.4.25.Final")

    // https://mvnrepository.com/artifact/org.jboss.weld/weld-junit5
    testImplementation("org.jboss.weld", "weld-junit5", "2.0.1.Final")
}
